### ISSUE TITLE
https://wss.node.glif.io/apigw/lotus/rpc/v0 should return application/json content-type

### ISSUE THREAD

**Issue by xinaxu** [glifio/filecoin-iac#122]
This response header is returned from https://api.node.glif.io/rpc/v0 but not the wss one.

**Comment by mur-me** [comment]
Thanks for the report @xinaxu, we will take a look and fix this!

**Comment by dumikau** [comment]
Hi! :)
I've prepared a fix for this issue and it will be applied after the migration. Thanks for the report!

**Comment by dumikau** [comment]
Btw, you can test the fix using this URL: https://wss.dev.node.glif.io/apigw/lotus/rpc/v0
But that's our dev environment, so the URL may be unavailable more often than available

**Comment by ArseniiPetrovich** [comment]
Solved after migration :)
