### ISSUE TITLE
Foundry: "Contract not Deploying"

### ISSUE THREAD

**Issue by ZakAyesh** [glifio/filecoin-iac#150]
I have been working with a community member to create a Foundry starter kit for the FEVM, but suddenly after this weekend the kit is returning "contract not deployed" errors even though the contracts are deploying (confirmed by looking at Hyperspace Filfox).  It was working before this weekend. The community member has confirmed this seems to be happening with other foundry projects.

Do you know if you all could have made any changes to the RPC that could be causing this? Hardhat seems to be working fine.

Network:
Hyperspace

Repo:
https://github.com/xBalbinus/fevm-foundry-kit#deploy-the-contracts

Command:
forge create

**Comment by ArseniiPetrovich** [comment]
I jumped into the node that runs for 15 days (even without restarts!), installed all the stuff inside and tried to deploy against localhost there. The error is the same.
It allowed me to verify the following:
- [x] It is not connected with how we setup the infra as I was inside the container running Lotus
- [x] It is not connected with when the node has started
And then, out of sudden... It just worked.
```
ubuntu@PETROVICHNB:~/fevm-foundry-kit$ forge create --rpc-url https://api.hyperspace.node.glif.io/rpc/v1 --private-key $PRIVATE_KEY --contracts /src/SimpleCoin.sol SimpleCoin --json -c 3141
{"deployer":"0x0186991db6a6Ea3c8cf0C9b6cBBeC1704B222BD7","deployedTo":"0x6b44449848af18bd0410AB9E2Be1D69473186775","transactionHash":"0x01df5cd745c49b91fcf68c1c3aa2e3ddf39647ce00138e3b8019c1df8c248dd5"}
```

And worked against the public API. I retried a couple of time and it is still working. To debug this further I would really need your input on how the verification process works in `forge`

**Comment by ArseniiPetrovich** [comment]
Reported as solved by @ZakAyesh. Solution was to add `-c 3141` argument.
