### ISSUE TITLE
Wrong reported amount of gas

### ISSUE THREAD

**Issue by xBalbinus** [glifio/filecoin-iac#152]
Issue: Hyperspace rpc returns wrong gas amount for network: existing deployments with the below gas amount is significantly underpriced.

Reproduction:

```
cast gas-price --rpc-url https://api.hyperspace.node.glif.io/rpc/v1
199668
```

`Error:
(code: 1, message: verify msg failed: message will not be included in a block: 'GasLimit' field cannot be less than the cost of storing a message on chain 315871 < 1025863, data: None)`

**Comment by ArseniiPetrovich** [comment]
Closing as not related to Glif - please, create an issue in Lotus repo.
